// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PJjEP9l_OS7rww617bBTT2u_jqM6HKY',
    appId: '1:561693149168:web:5878d4f64268ee015f7f35',
    messagingSenderId: '561693149168',
    projectId: 'mo-universe',
    authDomain: 'mo-universe.firebaseapp.com',
    databaseURL: 'https://mo-universe-default-rtdb.firebaseio.com',
    storageBucket: 'mo-universe.appspot.com',
    measurementId: 'G-QE6YNN2PKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1vFvHD1xUN9wjgLluoYOYuaWjwQcrXM',
    appId: '1:561693149168:android:217cc8571793ca195f7f35',
    messagingSenderId: '561693149168',
    projectId: 'mo-universe',
    databaseURL: 'https://mo-universe-default-rtdb.firebaseio.com',
    storageBucket: 'mo-universe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbYe2oj7GIiVJ9IxNfcEykYVcy3pSo-I',
    appId: '1:561693149168:ios:f77a20003d79471b5f7f35',
    messagingSenderId: '561693149168',
    projectId: 'mo-universe',
    databaseURL: 'https://mo-universe-default-rtdb.firebaseio.com',
    storageBucket: 'mo-universe.appspot.com',
    androidClientId: '561693149168-83b9nekjv5h048i47g2eva4qo0sarfj6.apps.googleusercontent.com',
    iosClientId: '561693149168-ib7kn0jgdohaadudctr3oame6reu4020.apps.googleusercontent.com',
    iosBundleId: 'com.MoUniverse.moUniverse',
  );
}
